-- 학습 세션: 실제로 공부한 구간 기록.
-- plan 은 nullable — 계획에 없던 공부도 기록되어야 통계가 현실과 맞는다.
-- 계획이 삭제돼도 "실제로 공부한 사실"은 남아야 하므로 on delete set null 을 쓴다.

create table study_session (
    id         bigint generated by default as identity,
    owner_id   bigint       not null,
    plan_id    bigint,
    category   varchar(20)  not null,
    study_date date         not null,
    started_at timestamp(6) not null,
    ended_at   timestamp(6),
    abandoned  boolean      not null default false,
    created_at timestamp(6),
    primary key (id),
    constraint fk_session_owner foreign key (owner_id) references member (id) on delete cascade,
    constraint fk_session_plan foreign key (plan_id) references plan (id) on delete set null
);

-- 통계·달력 조회는 항상 "회원 + 기간" 으로 들어온다
create index idx_session_owner_date on study_session (owner_id, study_date);

-- 진행 중(ended_at is null) 세션을 찾는 조회와 방치 세션 스캔에 쓰인다
create index idx_session_running on study_session (owner_id, ended_at);
