-- 비밀번호 재설정 토큰.
-- 리프레시 토큰과 같은 규칙: 원문은 메일로만 나가고 DB 에는 SHA-256 해시만 남긴다.
-- 회원이 삭제되면 함께 삭제된다.

create table password_reset_token (
    id         bigint       generated by default as identity,
    member_id  bigint       not null,
    token_hash varchar(64)  not null,
    expires_at timestamp(6) not null,
    created_at timestamp(6),
    primary key (id),
    constraint uk_password_reset_token_hash unique (token_hash),
    constraint fk_password_reset_token_member foreign key (member_id) references member (id) on delete cascade
);

-- 새 토큰을 낼 때 그 회원의 기존 토큰을 지우고, 만료분도 주기적으로 정리한다
create index idx_password_reset_token_member on password_reset_token (member_id);
create index idx_password_reset_token_expires on password_reset_token (expires_at);
