-- 스터디 그룹: 초대 코드로 모이는 소규모 모임.
--
-- 그룹장은 study_group.owner_id 로만 관리하고 group_member 에 role 컬럼을 두지 않는다 —
-- 같은 사실을 두 곳에 적으면 언젠가 어긋난다. 그룹장도 group_member 행을 가진다
-- (멤버 목록·같은 그룹 조회가 한 테이블로 끝나게).
--
-- 그룹이 지워지면 소속 관계도 의미가 없으므로 on delete cascade.
-- member 쪽은 cascade 를 걸지 않는다 — 회원 탈퇴는 행 삭제가 아니라 익명화이고,
-- 소속 정리는 애플리케이션(GroupCleanupListener)이 승계 규칙과 함께 처리해야 하기 때문이다.

create table study_group (
    id          bigint generated by default as identity,
    name        varchar(30)  not null,
    description varchar(200),
    invite_code varchar(10)  not null,
    owner_id    bigint       not null,
    created_at  timestamp(6),
    primary key (id),
    constraint uq_group_invite_code unique (invite_code),
    constraint fk_group_owner foreign key (owner_id) references member (id)
);

create table group_member (
    id        bigint generated by default as identity,
    group_id  bigint       not null,
    member_id bigint       not null,
    joined_at timestamp(6),
    primary key (id),
    constraint uq_group_member unique (group_id, member_id),
    constraint fk_gm_group foreign key (group_id) references study_group (id) on delete cascade,
    constraint fk_gm_member foreign key (member_id) references member (id)
);

-- "내가 속한 그룹"과 "같은 그룹인 사람" 조회가 전부 member_id 로 들어온다
create index idx_group_member_member on group_member (member_id);
