-- 회고: 그날(그 주) 무엇을 느꼈는지 남기는 한 줄.
--
-- 숫자만 쌓이는 통계는 "왜 그랬는지" 를 말해 주지 않는다.
-- 완료율이 낮은 주가 아팠던 주인지 계획을 과하게 잡은 주인지는 본인만 알고,
-- 적어 두지 않으면 다음 주에 같은 실수를 반복한다.
--
-- 같은 날짜에 두 개가 생기지 않게 (owner_id, type, target_date) 를 유니크로 묶는다 -
-- 회고는 새로 쌓는 게 아니라 그날 것을 고쳐 쓰는 것이다.
-- 주간 회고는 어느 요일에 쓰든 그 주 월요일로 맞춰 저장된다(RetroType.anchorDate).
--
-- 회고는 남에게 보이지 않는 개인 기록이라 익명으로 남길 이유가 없으므로,
-- 회원이 사라지면 함께 지운다(on delete cascade + RetrospectiveCleanupListener).

create table retrospective (
    id          bigint generated by default as identity,
    owner_id    bigint        not null,
    type        varchar(10)   not null,
    target_date date          not null,
    content     varchar(2000) not null,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    primary key (id),
    constraint uq_retro_owner_type_date unique (owner_id, type, target_date),
    constraint fk_retro_owner foreign key (owner_id) references member (id) on delete cascade
);

-- 조회는 항상 "회원 + 주기 + 기간" 으로 들어온다 (일간 뷰·주간 초안·돌아보기)
create index idx_retro_owner_type_date on retrospective (owner_id, type, target_date);
