-- 초기 스키마: 게시글, 첨부파일, 플랜, 알림

create table post (
    id         bigint generated by default as identity,
    title      varchar(200)  not null,
    writer     varchar(50)   not null,
    content    text          not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table attached_file (
    id            bigint generated by default as identity,
    original_name varchar(255) not null,
    stored_name   varchar(255) not null,
    content_type  varchar(255),
    size          bigint       not null,
    post_id       bigint,
    primary key (id),
    constraint uk_attached_file_stored_name unique (stored_name),
    constraint fk_attached_file_post foreign key (post_id) references post (id)
);

create table plan (
    id            bigint generated by default as identity,
    title         varchar(100) not null,
    content       varchar(1000),
    writer        varchar(50)  not null,
    plan_date     date         not null,
    start_time    time,
    end_time      time,
    completed     boolean      not null,
    shared        boolean      not null,
    reminder_sent boolean      not null,
    created_at    timestamp(6),
    updated_at    timestamp(6),
    primary key (id)
);

create table notification (
    id         bigint generated by default as identity,
    message    varchar(255) not null,
    url        varchar(100),
    read_flag  boolean      not null,
    created_at timestamp(6),
    primary key (id)
);
