-- 게시판 강화: 분류·좋아요·조회수.
--
-- 지금까지 인증글·질문·후기가 한 줄로 섞여 있어 무엇을 찾으려 해도 목록을 처음부터 훑어야 했다.
-- 분류를 뒤늦게 넣으므로 기존 글이 들어갈 자리(FREE)를 기본값으로 둔다 -
-- 어디에 둘지 정하지 않으면 not null 컬럼을 추가할 수 없다.

alter table post add column category varchar(20) not null default 'FREE';
alter table post add column view_count int not null default 0;
-- 좋아요 수는 post_like 를 매번 세지 않으려고 함께 드는 값이다. 진실은 아래 표에 있다.
alter table post add column like_count int not null default 0;

-- 분류 탭은 "분류 + 최신순" 으로만 조회한다
create index idx_post_category_id on post (category, id desc);

-- 좋아요: 누가 눌렀는지를 남겨야 "내가 눌렀는지" 를 알 수 있고, 두 번 눌리는 것도 막힌다.
-- 회원 행은 탈퇴해도 남지만(익명화), 좋아요는 개인 흔적이라 회원이 사라지면 함께 지운다.
create table post_like (
    id         bigint generated by default as identity,
    post_id    bigint not null,
    member_id  bigint not null,
    created_at timestamp(6),
    primary key (id),
    constraint uq_post_like unique (post_id, member_id),
    constraint fk_post_like_post foreign key (post_id) references post (id) on delete cascade,
    constraint fk_post_like_member foreign key (member_id) references member (id) on delete cascade
);

-- "이 사람이 누른 글" 조회(마이페이지·목록의 내 좋아요 표시)에 쓴다
create index idx_post_like_member on post_like (member_id);
