-- 이메일 인증.
--
-- 이메일은 선택 입력인데, 그 주소가 실제로 닿는지는 아무도 확인한 적이 없었다.
-- 오타가 있으면 비밀번호를 잊은 순간에야 알게 되고, 그때는 이미 고칠 방법이 없다.
--
-- 인증 여부를 회원 행에 두는 이유: 주소를 바꾸면 다시 미인증이 되어야 하는데,
-- 그 규칙은 주소와 같은 자리에 있어야 함께 바뀐다.
alter table member add column email_verified boolean not null default false;

-- 토큰 규칙은 비밀번호 재설정과 같다 - 원문은 메일로만 나가고 DB 에는 SHA-256 해시만 남는다.
-- 다른 점은 유효 시간뿐이다(재설정 30분 / 인증 24시간). 인증 메일은 급하게 눌러야 할 이유가 없고,
-- 메일함을 하루 뒤에 여는 일은 흔하다.
create table email_verification_token (
    id         bigint       generated by default as identity,
    member_id  bigint       not null,
    email      varchar(100) not null,
    token_hash varchar(64)  not null,
    expires_at timestamp(6) not null,
    created_at timestamp(6),
    primary key (id),
    constraint uk_email_verification_token_hash unique (token_hash),
    constraint fk_email_verification_token_member foreign key (member_id) references member (id) on delete cascade
);

-- 발급할 때 그 회원의 이전 토큰을 지우고, 만료분은 새벽에 정리한다
create index idx_email_verification_token_member on email_verification_token (member_id);
create index idx_email_verification_token_expires on email_verification_token (expires_at);
