-- 회원 테이블: JWT 로그인 도입

create table member (
    id         bigint generated by default as identity,
    login_id   varchar(30)  not null,
    password   varchar(100) not null,
    nickname   varchar(30)  not null,
    created_at timestamp(6),
    primary key (id),
    constraint uk_member_login_id unique (login_id),
    constraint uk_member_nickname unique (nickname)
);
