-- 그룹 응원.
--
-- 그룹 화면에는 이번 주 순위와 챌린지 달성만 있었다. 순위는 상위권을 더 뛰게 하지만
-- 하위권을 조용히 떠나게 한다 - 비경쟁 상호작용이 하나도 없었다.
-- 응원은 순위와 반대 방향으로 작동한다: 누구에게나 보낼 수 있고, 받는 쪽에 손해가 없다.
--
-- 하루 한 번으로 묶는 이유(uq_cheer_daily):
-- 제한이 없으면 버튼을 연타해 알림을 무한히 찍어낼 수 있다. 공유 알림에서 이미 겪은 문제다
-- (plan.share_notified). 그리고 "오늘 이미 응원했다" 는 화면이 버튼을 잠그는 기준이기도 하다.
--
-- member 쪽에 cascade 를 걸지 않는 이유는 group_member 와 같다 -
-- 회원 탈퇴는 행 삭제가 아니라 익명화이고, 정리는 애플리케이션이 맡는다.
create table cheer (
    id           bigint generated by default as identity,
    group_id     bigint not null,
    sender_id    bigint not null,
    recipient_id bigint not null,
    cheer_date   date   not null,
    created_at   timestamp(6),
    primary key (id),
    constraint uq_cheer_daily unique (group_id, sender_id, recipient_id, cheer_date),
    constraint fk_cheer_group foreign key (group_id) references study_group (id) on delete cascade,
    constraint fk_cheer_sender foreign key (sender_id) references member (id),
    constraint fk_cheer_recipient foreign key (recipient_id) references member (id)
);

-- "오늘 이 그룹에서 내가 누구를 응원했나" - 그룹 화면을 열 때마다 도는 조회다
create index idx_cheer_today on cheer (group_id, sender_id, cheer_date);

-- 응원 알림 설정. 기본 켜짐 - 받는 쪽에 손해가 없는 알림이고, 하루 한 번으로 묶여 소음이 되지 않는다.
alter table member add column cheer_enabled boolean not null default true;
