-- 지원 현황.
--
-- 취준생이 실제로 가장 많이 관리하는 것 - 어느 회사에 넣었고, 지금 어느 단계이고, 언제까지인지 -
-- 를 담을 자리가 없어서 다들 엑셀을 따로 썼다. 계획과 기록은 여기 있는데 그 기록을 왜 쌓는지가
-- 저기 있으면 둘 다 반쪽이 된다.
--
-- 단계(stage)를 문자열 enum 으로 두는 이유: 회사마다 전형 이름이 다르지만 준비하는 일은
-- 몇 갈래로 모인다. 자유 입력이면 같은 단계가 열 가지 이름으로 쌓여 분류별 학습량과 이을 수 없다.
--
-- 마감일이 하나뿐인 이유: 단계마다 날짜를 다 들고 있으면 입력이 다섯 칸이 되고, 그러면 아무도
-- 채우지 않는다. 지금 필요한 것은 '다음 날짜' 하나다.
--
-- owner 에 cascade 를 걸지 않는다 - 회원 탈퇴는 행 삭제가 아니라 익명화이고,
-- 정리는 애플리케이션(JobApplicationCleanupListener)이 맡는다. D-Day 와 같은 규칙이다.
create table job_application (
    id         bigint generated by default as identity,
    owner_id   bigint       not null,
    company    varchar(50)  not null,
    -- 'position' 은 SQL 표준의 함수 이름이라 벤더에 따라 식별자로 쓰기 까다롭다.
    -- 컬럼 이름만 피해 두고 코드에서는 position 으로 읽는다.
    job_position varchar(50),
    stage      varchar(20)  not null,
    result     varchar(20)  not null,
    deadline   date,
    memo       varchar(500),
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id),
    constraint fk_job_application_owner foreign key (owner_id) references member (id)
);

-- "내 지원 목록" 과 "곧 마감인 것" 이 전부 이 두 컬럼으로 들어온다 (dday 와 같은 모양)
create index idx_job_application_owner on job_application (owner_id, deadline);
