-- 댓글: 게시글 또는 공유 플랜 중 정확히 하나에 달린다.
-- 대상 글/플랜이 삭제되면 댓글도 함께 삭제 (on delete cascade).

create table comments (
    id         bigint generated by default as identity,
    post_id    bigint,
    plan_id    bigint,
    author_id  bigint       not null,
    content    varchar(500) not null,
    created_at timestamp(6),
    primary key (id),
    constraint fk_comments_post foreign key (post_id) references post (id) on delete cascade,
    constraint fk_comments_plan foreign key (plan_id) references plan (id) on delete cascade,
    constraint fk_comments_author foreign key (author_id) references member (id),
    constraint ck_comments_single_target check ((post_id is null) <> (plan_id is null))
);
