-- 리프레시 토큰: 원문이 아닌 SHA-256 해시를 저장하고, 로그아웃 시 행을 삭제해 즉시 무효화한다.
-- 회원이 삭제되면 토큰도 함께 삭제된다.

create table refresh_token (
    id         bigint generated by default as identity,
    member_id  bigint      not null,
    token_hash varchar(64) not null,
    expires_at timestamp(6) not null,
    created_at timestamp(6),
    primary key (id),
    constraint uk_refresh_token_hash unique (token_hash),
    constraint fk_refresh_token_member foreign key (member_id) references member (id) on delete cascade
);
