-- D-Day: 시험·면접 등 목표일 카운트다운. 회원이 삭제되면 함께 삭제된다.

create table dday (
    id          bigint generated by default as identity,
    owner_id    bigint      not null,
    title       varchar(50) not null,
    target_date date        not null,
    created_at  timestamp(6),
    primary key (id),
    constraint fk_dday_owner foreign key (owner_id) references member (id) on delete cascade
);

create index idx_dday_owner_target on dday (owner_id, target_date);
